import { IKPItem, IKKItem, KomponenPenilaian, LKEItem, KKEPDItem, SakipDocument, User } from '../types';

export const INITIAL_USERS: (User & { passwordHash: string })[] = [
  {
    id: 'user-admin-1',
    name: 'Administrator SAKIP',
    email: 'sakip.transnakerlutra@gmail.com',
    passwordHash: 'admin123',
    role: 'admin',
    bidang: 'Sekretariat Dinas',
    nip: '19790514 200502 1 003',
    createdAt: '2024-01-05',
  },
  {
    id: 'user-op-1',
    name: 'Operator Pemberdayaan Tenaga Kerja',
    email: 'pemberdayaan.tk@luwuutarakab.go.id',
    passwordHash: 'operator123',
    role: 'operator',
    bidang: 'Bidang Pemberdayaan Tenaga Kerja',
    nip: '19881122 201101 2 005',
    createdAt: '2024-01-12',
  },
  {
    id: 'user-op-2',
    name: 'Operator Hubungan Industrial',
    email: 'hi.transnaker@luwuutarakab.go.id',
    passwordHash: 'operator123',
    role: 'operator',
    bidang: 'Bidang Hubungan Industrial',
    nip: '19900418 201402 1 002',
    createdAt: '2024-01-15',
  },
  {
    id: 'user-op-3',
    name: 'Operator Penyiapan & Pembangunan Kawasan',
    email: 'penyiapan.trans@luwuutarakab.go.id',
    passwordHash: 'operator123',
    role: 'operator',
    bidang: 'Bidang Penyiapan dan Pembangunan Kawasan Transmigrasi',
    nip: '19860724 201001 1 008',
    createdAt: '2024-01-20',
  },
  {
    id: 'user-op-4',
    name: 'Operator Pengembangan Kawasan',
    email: 'pengembangan.trans@luwuutarakab.go.id',
    passwordHash: 'operator123',
    role: 'operator',
    bidang: 'Bidang Pengembangan Kawasan Transmigrasi',
    nip: '19910905 201503 2 003',
    createdAt: '2024-01-22',
  },
  {
    id: 'user-op-5',
    name: 'Operator Program & Evaluasi',
    email: 'operator.transnaker@luwuutarakab.go.id',
    passwordHash: 'operator123',
    role: 'operator',
    bidang: 'Sekretariat Dinas',
    nip: '19920310 201903 1 002',
    createdAt: '2024-02-01',
  },
];

export const INITIAL_IKP: IKPItem[] = [
  {
    id: 'ikp-1',
    kode: 'IKP-01',
    sasaranProgram: 'Meningkatnya Kualitas dan Produktivitas Tenaga Kerja Daerah',
    indikator: 'Persentase Tenaga Kerja Terlatih yang Diserap Pasar Kerja',
    satuan: '%',
    targetTahunan: 75.0,
    targetTW1: 20.0,
    realisasiTW1: 22.5,
    targetTW2: 40.0,
    realisasiTW2: 42.0,
    targetTW3: 60.0,
    realisasiTW3: 63.5,
    targetTW4: 75.0,
    realisasiTW4: 0,
    capaianAkhir: 84.6,
    status: 'Tercapai',
    penanggungJawab: 'Bidang Pemberdayaan Tenaga Kerja',
    keterangan: 'Pelatihan Unit Kompetensi Kejuruan Teknik Las & Tata Boga UPTD BLK Luwu Utara tuntas tahap III.',
    tahun: 2024,
  },
  {
    id: 'ikp-2',
    kode: 'IKP-02',
    sasaranProgram: 'Terwujudnya Hubungan Industrial yang Harmonis dan Perlindungan Jaminan Sosial Ketenagakerjaan',
    indikator: 'Persentase Kasus Perselisihan Hubungan Industrial yang Diselesaikan Secara Mufakat',
    satuan: '%',
    targetTahunan: 90.0,
    targetTW1: 25.0,
    realisasiTW1: 25.0,
    targetTW2: 50.0,
    realisasiTW2: 52.0,
    targetTW3: 75.0,
    realisasiTW3: 78.0,
    targetTW4: 90.0,
    realisasiTW4: 0,
    capaianAkhir: 86.7,
    status: 'Tercapai',
    penanggungJawab: 'Bidang Hubungan Industrial',
    keterangan: 'Semua mediasi perselisihan bipartit dan tripartit di sektor perkebunan dan agroindustri terfasilitasi aman.',
    tahun: 2024,
  },
  {
    id: 'ikp-3',
    kode: 'IKP-03',
    sasaranProgram: 'Terwujudnya Kesiapan Infrastruktur dan Permukiman Kawasan Transmigrasi Layak Huni',
    indikator: 'Persentase Penyediaan Sarana Prasarana dan Kesiapan Lahan Kawasan Transmigrasi',
    satuan: '%',
    targetTahunan: 85.0,
    targetTW1: 20.0,
    realisasiTW1: 22.0,
    targetTW2: 45.0,
    realisasiTW2: 44.0,
    targetTW3: 70.0,
    realisasiTW3: 68.5,
    targetTW4: 85.0,
    realisasiTW4: 0,
    capaianAkhir: 80.6,
    status: 'Tercapai',
    penanggungJawab: 'Bidang Penyiapan dan Pembangunan Kawasan Transmigrasi',
    keterangan: 'Pematangan lahan perumahan dan jalan poros poros penghubung UPT transmigrasi sesuai rencana teknis.',
    tahun: 2024,
  },
  {
    id: 'ikp-4',
    kode: 'IKP-04',
    sasaranProgram: 'Meningkatnya Kemandirian dan Pertumbuhan Ekonomi Warga Kawasan Transmigrasi',
    indikator: 'Persentase Kawasan Transmigrasi yang Berstatus Berkembang dan Mandiri',
    satuan: '%',
    targetTahunan: 80.0,
    targetTW1: 20.0,
    realisasiTW1: 20.0,
    targetTW2: 40.0,
    realisasiTW2: 38.0,
    targetTW3: 65.0,
    realisasiTW3: 62.0,
    targetTW4: 80.0,
    realisasiTW4: 0,
    capaianAkhir: 77.5,
    status: 'Perlu Perhatian',
    penanggungJawab: 'Bidang Pengembangan Kawasan Transmigrasi',
    keterangan: 'Percepatan sertipikasi tanah transmigrasi dan penguatan kelembagaan kelompok tani komoditas jagung & kelapa sawit.',
    tahun: 2024,
  },
  {
    id: 'ikp-5',
    kode: 'IKP-05',
    sasaranProgram: 'Terwujudnya Tata Kelola Pemerintahan yang Akuntabel dan Pelayanan Publik Prima',
    indikator: 'Nilai Evaluasi SAKIP Dinas Transmigrasi dan Tenaga Kerja',
    satuan: 'Poin',
    targetTahunan: 78.5,
    targetTW1: 65.0,
    realisasiTW1: 68.0,
    targetTW2: 72.0,
    realisasiTW2: 74.5,
    targetTW3: 76.0,
    realisasiTW3: 77.8,
    targetTW4: 78.5,
    realisasiTW4: 0,
    capaianAkhir: 99.1,
    status: 'Tercapai',
    penanggungJawab: 'Sekretariat Dinas',
    keterangan: 'Predikat capaian predikat BB menuju target predikat A dari Tim Evaluasi Inspektorat Daerah Luwu Utara.',
    tahun: 2024,
  }
];

export const INITIAL_IKK: IKKItem[] = [
  {
    id: 'ikk-1',
    kode: 'IKK-01',
    program: 'Program Penunjang Urusan Pemerintahan Daerah Kabupaten/Kota',
    kegiatan: 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah',
    indikatorKegiatan: 'Persentase dokumen perencanaan SAKIP dan pelaporan berkala yang tersusun tepat regulasi',
    satuan: '%',
    bidang: 'Sekretariat Dinas',
    target: 100,
    realisasi: 100,
    persenCapaian: 100.0,
    anggaran: 145000000,
    realisasiAnggaran: 142300000,
    penanggungJawab: 'Kasubbag Perencanaan & Pelaporan',
    tahun: 2024,
  },
  {
    id: 'ikk-2',
    kode: 'IKK-02',
    program: 'Program Pelatihan Kerja dan Produktivitas Tenaga Kerja',
    kegiatan: 'Pelaksanaan Pelatihan Berdasarkan Unit Kompetensi di BLK',
    indikatorKegiatan: 'Jumlah pencari kerja yang memiliki sertifikat kompetensi kerja BNSP',
    satuan: 'Orang',
    bidang: 'Bidang Pemberdayaan Tenaga Kerja',
    target: 160,
    realisasi: 144,
    persenCapaian: 90.0,
    anggaran: 285000000,
    realisasiAnggaran: 265000000,
    penanggungJawab: 'Kepala Bidang Pemberdayaan Tenaga Kerja',
    tahun: 2024,
  },
  {
    id: 'ikk-3',
    kode: 'IKK-03',
    program: 'Program Penempatan Tenaga Kerja dan Perluasan Kesempatan Kerja',
    kegiatan: 'Pelayanan Antarkerja di Daerah Kabupaten/Kota (Kartu AK-1 & Fasilitasi Kerja)',
    indikatorKegiatan: 'Jumlah pencari kerja terdaftar yang mendapatkan fasilitasi penempatan kerja',
    satuan: 'Orang',
    bidang: 'Bidang Pemberdayaan Tenaga Kerja',
    target: 350,
    realisasi: 320,
    persenCapaian: 91.4,
    anggaran: 120000000,
    realisasiAnggaran: 110500000,
    penanggungJawab: 'Kasi Penempatan Tenaga Kerja',
    tahun: 2024,
  },
  {
    id: 'ikk-4',
    kode: 'IKK-04',
    program: 'Program Hubungan Industrial dan Jaminan Sosial Tenaga Kerja',
    kegiatan: 'Pembinaan Penerapan Syarat Kerja, PKB, dan Kepesertaan Jamsostek',
    indikatorKegiatan: 'Jumlah perusahaan yang dilakukan pembinaan kepatuhan syarat kerja & norma ketenagakerjaan',
    satuan: 'Perusahaan',
    bidang: 'Bidang Hubungan Industrial',
    target: 45,
    realisasi: 42,
    persenCapaian: 93.3,
    anggaran: 95000000,
    realisasiAnggaran: 88700000,
    penanggungJawab: 'Kepala Bidang Hubungan Industrial',
    tahun: 2024,
  },
  {
    id: 'ikk-5',
    kode: 'IKK-05',
    program: 'Program Hubungan Industrial dan Jaminan Sosial Tenaga Kerja',
    kegiatan: 'Pencegahan dan Penyelesaian Perselisihan Hubungan Industrial',
    indikatorKegiatan: 'Persentase aduan dan perselisihan ketenagakerjaan yang diselesaikan secara damai/mediasi',
    satuan: '%',
    bidang: 'Bidang Hubungan Industrial',
    target: 100,
    realisasi: 95,
    persenCapaian: 95.0,
    anggaran: 75000000,
    realisasiAnggaran: 68500000,
    penanggungJawab: 'Mediator Hubungan Industrial',
    tahun: 2024,
  },
  {
    id: 'ikk-6',
    kode: 'IKK-06',
    program: 'Program Penyiapan dan Pembangunan Kawasan Transmigrasi',
    kegiatan: 'Penyusunan Rencana Teknis Tata Ruang dan Pembangunan Sarana Prasarana Permukiman',
    indikatorKegiatan: 'Jumlah lokasi satuan permukiman transmigrasi yang siap huni dan berinfrastruktur memadai',
    satuan: 'Lokasi',
    bidang: 'Bidang Penyiapan dan Pembangunan Kawasan Transmigrasi',
    target: 3,
    realisasi: 3,
    persenCapaian: 100.0,
    anggaran: 340000000,
    realisasiAnggaran: 318000000,
    penanggungJawab: 'Kepala Bidang Penyiapan & Pembangunan Kawasan',
    tahun: 2024,
  },
  {
    id: 'ikk-7',
    kode: 'IKK-07',
    program: 'Program Pengembangan Kawasan Transmigrasi',
    kegiatan: 'Pemberdayaan Usaha Ekonomi, Fasilitasi Legalitas Lahan, dan Pembinaan Warga Transmigrasi',
    indikatorKegiatan: 'Jumlah kelompok binaan tani transmigrasi aktif berproduksi komoditas unggulan daerah',
    satuan: 'Kelompok',
    bidang: 'Bidang Pengembangan Kawasan Transmigrasi',
    target: 15,
    realisasi: 14,
    persenCapaian: 93.3,
    anggaran: 260000000,
    realisasiAnggaran: 242000000,
    penanggungJawab: 'Kepala Bidang Pengembangan Kawasan Transmigrasi',
    tahun: 2024,
  },
];

export const INITIAL_KOMPONEN_PENILAIAN: KomponenPenilaian[] = [
  {
    id: 'komp-1',
    kode: 'PK',
    nama: 'Perencanaan Kinerja',
    bobot: 30,
    nilai: 82.5,
    nilaiTertimbang: 24.75,
    subkomponen: [
      { id: 'sub-1a', nama: 'Dokumen Renstra memenuhi standar & terintegrasi IKU', bobot: 10, nilai: 84.0, keterangan: 'Telah direviu selaras dengan RPJMD Luwu Utara' },
      { id: 'sub-1b', nama: 'Penyusunan Perjanjian Kinerja (PK) berjenjang (Cascading)', bobot: 10, nilai: 83.0, keterangan: 'Tercantum PK Eselon II, III, dan Subkoordinator' },
      { id: 'sub-1c', nama: 'Kualitas penetapan indikator target SMART', bobot: 10, nilai: 80.5, keterangan: 'Capaian target dilengkapi rincian triwulanan' },
    ],
    catatanRekomendasi: 'Pertahankan cascading indikator kinerja hingga pelaksana operasional.',
  },
  {
    id: 'komp-2',
    kode: 'PG',
    nama: 'Pengukuran Kinerja',
    bobot: 30,
    nilai: 79.0,
    nilaiTertimbang: 23.70,
    subkomponen: [
      { id: 'sub-2a', nama: 'Pengumpulan data kinerja berkala dan validitas data', bobot: 10, nilai: 80.0, keterangan: 'Data dukung diarsipkan rapi melalui portal LAPAK KINERJA' },
      { id: 'sub-2b', nama: 'Pemanfaatan data kinerja dalam pengambilan keputusan', bobot: 10, nilai: 78.0, keterangan: 'Notulensi rapat evaluasi bulanan memuat tindak lanjut' },
      { id: 'sub-2c', nama: 'Sistem aplikasi pengukuran kinerja digital', bobot: 10, nilai: 79.0, keterangan: 'Telah difasilitasi pemantauan digital real-time' },
    ],
    catatanRekomendasi: 'Optimalkan verifikasi data dukung sebelum diunggah ke aplikasi.',
  },
  {
    id: 'komp-3',
    kode: 'PL',
    nama: 'Pelaporan Kinerja',
    bobot: 15,
    nilai: 81.0,
    nilaiTertimbang: 12.15,
    subkomponen: [
      { id: 'sub-3a', nama: 'Kualitas dan ketepatan waktu penyampaian LKjIP', bobot: 7.5, nilai: 82.0, keterangan: 'LKjIP diserahkan ke Inspektorat & Bappelitbangda tepat waktu' },
      { id: 'sub-3b', nama: 'Analisis efisiensi penggunaan sumber daya & anggaran', bobot: 7.5, nilai: 80.0, keterangan: 'Memuat perbandingan target, realisasi, dan efisiensi biaya' },
    ],
    catatanRekomendasi: 'Sertakan komparasi kinerja antar tahun anggaran yang lebih komprehensif.',
  },
  {
    id: 'komp-4',
    kode: 'EI',
    nama: 'Evaluasi Internal',
    bobot: 10,
    nilai: 76.5,
    nilaiTertimbang: 7.65,
    subkomponen: [
      { id: 'sub-4a', nama: 'Pemantauan berkala pencapaian kinerja oleh pimpinan', bobot: 5.0, nilai: 77.0, keterangan: 'Monev triwulanan dipimpin Kepala Dinas' },
      { id: 'sub-4b', nama: 'Tindak lanjut rekomendasi hasil evaluasi internal/inspektorat', bobot: 5.0, nilai: 76.0, keterangan: 'Matriks tindak lanjut LHP telah ditindaklanjuti 92%' },
    ],
    catatanRekomendasi: 'Tingkatkan dokumentasi notulensi dan daftar hadir monev berkala.',
  },
  {
    id: 'komp-5',
    kode: 'CK',
    nama: 'Capaian Kinerja',
    bobot: 15,
    nilai: 82.0,
    nilaiTertimbang: 12.30,
    subkomponen: [
      { id: 'sub-5a', nama: 'Capaian IKU dan sasaran strategis dinas', bobot: 8.0, nilai: 83.0, keterangan: 'Mayoritas indikator IKP melampaui 80% per TW III' },
      { id: 'sub-5b', nama: 'Prestasi inovasi pelayanan dan akuntabilitas', bobot: 7.0, nilai: 81.0, keterangan: 'Implementasi LAPAK KINERJA meningkatkan responsivitas' },
    ],
    catatanRekomendasi: 'Pertahankan target sertipikasi kompetensi tenaga kerja lokal.',
  },
];

export const INITIAL_LKE_ITEMS: LKEItem[] = [
  {
    id: 'lke-1',
    komponen: 'Perencanaan Kinerja',
    subkomponen: 'Kualitas Renstra',
    kriteria: 'Keberadaan dan keselarasan Renstra Perangkat Daerah dengan RPJMD Kabupaten',
    parameter: 'Renstra memuat tujuan, sasaran, indikator berorientasi hasil yang selaras dengan RPJMD Luwu Utara',
    bobot: 5,
    nilai: 85,
    nilaiAkhir: 4.25,
    statusDukung: 'Lengkap',
    dokumenTerkait: ['Renstra Dinas Transnaker 2021-2026', 'SK Penetapan IKU Dinas'],
    linkEvidence: 'https://transnaker.luwuutarakab.go.id/sakip/renstra-2021-2026.pdf',
    tautanDokumenId: 'doc-renstra',
    catatanEvaluator: 'Sangat baik, cascading sasaran strategis telah memenuhi PermenPAN-RB No 88.',
  },
  {
    id: 'lke-2',
    komponen: 'Perencanaan Kinerja',
    subkomponen: 'Perjanjian Kinerja (PK)',
    kriteria: 'Penetapan Perjanjian Kinerja berjenjang setiap awal tahun anggaran',
    parameter: 'Perjanjian Kinerja ditandatangani tepat waktu dan berjenjang dari Kepala Dinas hingga Subkoordinator',
    bobot: 5,
    nilai: 82,
    nilaiAkhir: 4.10,
    statusDukung: 'Lengkap',
    dokumenTerkait: ['Perjanjian Kinerja Kepala Dinas 2024', 'PK Eselon III & IV'],
    linkEvidence: 'https://transnaker.luwuutarakab.go.id/sakip/pk-transnaker-2024.pdf',
    tautanDokumenId: 'doc-pk',
    catatanEvaluator: 'Lengkap, sudah dilampirkan lembar pengesahan resmi.',
  },
  {
    id: 'lke-3',
    komponen: 'Pengukuran Kinerja',
    subkomponen: 'Mekanisme Pengukuran',
    kriteria: 'Pengukuran kinerja dilakukan secara berkala dan teratur (Triwulanan)',
    parameter: 'Tersedia data capaian kinerja berkala beserta formulir kendali pengisian',
    bobot: 6,
    nilai: 80,
    nilaiAkhir: 4.80,
    statusDukung: 'Lengkap',
    dokumenTerkait: ['Laporan Monev Triwulan II 2024', 'Matriks Renaksi TW III'],
    linkEvidence: 'https://drive.google.com/drive/folders/monev-triwulan2-transnaker-lutra',
    tautanDokumenId: 'doc-monev',
    catatanEvaluator: 'Data capaian triwulanan telah diverifikasi oleh Subbag Program.',
  },
  {
    id: 'lke-4',
    komponen: 'Pelaporan Kinerja',
    subkomponen: 'Kualitas LKjIP',
    kriteria: 'Penyajian LKjIP menyajikan informasi menyeluruh tentang keberhasilan dan kegagalan kinerja',
    parameter: 'LKjIP menguraikan analisis penyebab disparitas target-realisasi dan alternatif solusi efisiensi anggaran',
    bobot: 6,
    nilai: 80,
    nilaiAkhir: 4.80,
    statusDukung: 'Lengkap',
    dokumenTerkait: ['LKjIP Dinas Transnaker 2023'],
    linkEvidence: 'https://transnaker.luwuutarakab.go.id/sakip/lkjip-transnaker-2023.pdf',
    tautanDokumenId: 'doc-lkjip',
    catatanEvaluator: 'Bab analisis efisiensi penggunaan sumber daya telah disajikan terperinci.',
  },
  {
    id: 'lke-5',
    komponen: 'Evaluasi Internal',
    subkomponen: 'Monev Kinerja',
    kriteria: 'Pelaksanaan evaluasi internal secara berkala dan perumusan rekomendasi perbaikan',
    parameter: 'Terdapat risalah rapat monev berkala dan tindak lanjut rekomendasi triwulanan',
    bobot: 4,
    nilai: 75,
    nilaiAkhir: 3.00,
    statusDukung: 'Perlu Perbaikan',
    dokumenTerkait: ['Notulensi Rapat Evaluasi Kinerja Internal'],
    linkEvidence: 'https://drive.google.com/file/d/notulensi-monev-internal-2024',
    tautanDokumenId: 'doc-monev',
    catatanEvaluator: 'Daftar hadir dan foto dokumentasi evaluasi internal triwulan II perlu dilengkapi.',
  },
  {
    id: 'lke-6',
    komponen: 'Capaian Kinerja',
    subkomponen: 'Kinerja Aktual',
    kriteria: 'Pencapaian target sasaran strategis program prioritas daerah',
    parameter: 'Rata-rata realisasi indikator kinerja program utama mencapai di atas 80%',
    bobot: 4,
    nilai: 84,
    nilaiAkhir: 3.36,
    statusDukung: 'Lengkap',
    dokumenTerkait: ['Capaian IKP Triwulan III', 'Rekapitulasi Pelatihan BLK'],
    linkEvidence: 'https://transnaker.luwuutarakab.go.id/sakip/capaian-kinerja-tw3-2024.xlsx',
    tautanDokumenId: 'doc-renja',
    catatanEvaluator: 'Capaian penempatan tenaga kerja dan pembinaan transmigrasi melampaui target berkala.',
  },
];

export const INITIAL_KKE_PD: KKEPDItem[] = [
  {
    id: 'kke-1',
    kode: 'KKE-PD-01',
    aspek: 'Perencanaan Strategis',
    indikator: 'Kesesuaian Tujuan dan Sasaran dengan Isu Strategis Daerah',
    pertanyaan: 'Apakah tujuan dan sasaran pada Renstra Dinas Transnaker telah merespon isu ketenagakerjaan dan transmigrasi Luwu Utara?',
    kriteriaA: 'Sangat Sesuai: Menjawab 100% isu strategis dengan indikator dampak (outcome)',
    kriteriaB: 'Sesuai: Menjawab sebagian besar isu dengan indikator terukur',
    kriteriaC: 'Cukup: Sasaran masih berorientasi output kegiatan',
    pilihan: 'A',
    skor: 90,
    dataDukungDiunggah: 'Dokumen Renstra 2021-2026 Bab IV & Bab V',
    tautanDokumenId: 'doc-renstra',
    linkEvidence: 'https://transnaker.luwuutarakab.go.id/sakip/renstra-2021-2026.pdf',
    catatanTimSAKIP: 'Rumusan tujuan terhubung langsung dengan visi RPJMD Kab. Luwu Utara.',
    rekomendasiPerbaikan: 'Terus perkuat indikator kesejahteraan transmigran mandiri.',
  },
  {
    id: 'kke-2',
    kode: 'KKE-PD-02',
    aspek: 'Cascading Kinerja',
    indikator: 'Pohon Kinerja dan Matriks Pembagian Peran Hasil (Cascading)',
    pertanyaan: 'Apakah terdapat pohon kinerja (cascading) yang menggambarkan penjabaran kinerja Kepala Dinas ke pejabat administrator dan pengawas?',
    kriteriaA: 'Terdapat cascading vertikal dan horizontal yang jelas hingga level staf pelaksana',
    kriteriaB: 'Terdapat cascading hanya sampai tingkat Eselon III/Kepala Bidang',
    kriteriaC: 'Cascading belum lengkap atau tidak berjenjang logis',
    pilihan: 'A',
    skor: 88,
    dataDukungDiunggah: 'Bagan Cascading / Pohon Kinerja Dinas Transnaker 2024',
    tautanDokumenId: 'doc-iku',
    linkEvidence: 'https://transnaker.luwuutarakab.go.id/sakip/pohon-kinerja-cascading-2024.pdf',
    catatanTimSAKIP: 'Pohon kinerja telah ditandatangani Kepala Dinas dan selaras lintas bidang.',
    rekomendasiPerbaikan: 'Perbarui pohon kinerja apabila ada mutasi atau perubahan nomenklatur program.',
  },
  {
    id: 'kke-3',
    kode: 'KKE-PD-03',
    aspek: 'Pengukuran dan Pemanfaatan Data',
    indikator: 'Ketersediaan Manual Indikator Kinerja Utama (IKU)',
    pertanyaan: 'Apakah setiap indikator kinerja telah dilengkapi dengan Definisi Operasional, Formula Perhitungan, dan Sumber Data yang valid?',
    kriteriaA: '100% indikator dilengkapi Formulir Manual IKU terperinci dan ditandatangani',
    kriteriaB: 'Sebagian besar indikator (≥80%) memiliki manual indikator',
    kriteriaC: 'Manual indikator belum tersusun lengkap',
    pilihan: 'B',
    skor: 82,
    dataDukungDiunggah: 'Buku Manual Indikator Kinerja Utama (IKU) Dinas Transnaker',
    tautanDokumenId: 'doc-iku',
    linkEvidence: 'https://transnaker.luwuutarakab.go.id/sakip/manual-iku-transnaker-2024.pdf',
    catatanTimSAKIP: 'Manual IKU untuk subkegiatan pelatihan kerja perlu penajaman formula penyerapan.',
    rekomendasiPerbaikan: 'Lengkapi lembar pengesahan Kepala Dinas pada lampiran manual indikator.',
  },
  {
    id: 'kke-4',
    kode: 'KKE-PD-04',
    aspek: 'Pelaporan Akuntabilitas',
    indikator: 'Analisis Komparasi Kinerja dan Efisiensi Sumber Daya',
    pertanyaan: 'Apakah pelaporan kinerja (LKjIP) menyajikan perbandingan realisasi dengan tahun-tahun sebelumnya dan efisiensi anggaran?',
    kriteriaA: 'Menyajikan tren 3 tahun terakhir, analisis efisiensi biaya, dan rekomendasi perbaikan',
    kriteriaB: 'Menyajikan komparasi 2 tahun terakhir dengan analisis efisiensi memadai',
    kriteriaC: 'Hanya menyajikan realisasi tahun berjalan tanpa analisis efisiensi',
    pilihan: 'A',
    skor: 85,
    dataDukungDiunggah: 'LKjIP 2023 Bab III Analisis Akuntabilitas Kinerja',
    tautanDokumenId: 'doc-lkjip',
    linkEvidence: 'https://transnaker.luwuutarakab.go.id/sakip/lkjip-transnaker-2023.pdf',
    catatanTimSAKIP: 'Penyajian tabel perbandingan dan efisiensi belanja kegiatan sangat rinci.',
    rekomendasiPerbaikan: 'Pertahankan format penyajian grafik pada laporan tahun berikutnya.',
  },
  {
    id: 'kke-5',
    kode: 'KKE-PD-05',
    aspek: 'Evaluasi Internal & Tindak Lanjut',
    indikator: 'Pemantauan Realisasi Rencana Aksi (Renaksi)',
    pertanyaan: 'Apakah dilakukan monitoring berkala atas capaian rencana aksi kinerja setiap triwulan oleh pimpinan unit kerja?',
    kriteriaA: 'Dilakukan rapat monev berkala setiap triwulan disertai bukti notulensi, absensi, dan matriks RTL',
    kriteriaB: 'Dilakukan monev per semester',
    kriteriaC: 'Monev hanya dilakukan pada akhir tahun anggaran',
    pilihan: 'A',
    skor: 84,
    dataDukungDiunggah: 'Laporan Monev Triwulan II & Risalah Rapat Pembahasan Kinerja',
    tautanDokumenId: 'doc-monev',
    linkEvidence: 'https://drive.google.com/drive/folders/monev-tw2-transnaker-lutra',
    catatanTimSAKIP: 'Rapat monev triwulanan telah diagendakan rutin dipimpin Kepala Dinas.',
    rekomendasiPerbaikan: 'Pastikan matriks tindak lanjut diisi secara berkala di LAPAK KINERJA.',
  },
];

export const INITIAL_DOCUMENTS: SakipDocument[] = [
  {
    id: 'doc-renstra',
    title: 'Rencana Strategis (RENSTRA) Dinas Transnaker Kabupaten Luwu Utara 2021-2026',
    kategori: 'RENSTRA',
    tahun: 2024,
    bidang: 'Sekretariat Dinas',
    fileName: 'RENSTRA_Transnaker_Luwu_Utara_2021_2026.pdf',
    fileType: 'pdf',
    fileSize: '3.8 MB',
    uploadedBy: 'Administrator SAKIP',
    uploadedAt: '2024-03-15 09:30',
    deskripsi: 'Dokumen Renstra resmi yang memuat visi misi, tujuan strategis, indikator kinerja program, dan kerangka pendanaan 5 tahunan seluruh unit kerja.',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '560/014/DIS-TRANSNAKER/2021',
  },
  {
    id: 'doc-iku',
    title: 'Indikator Kinerja Utama (IKU) Dinas Transmigrasi dan Tenaga Kerja',
    kategori: 'IKU',
    tahun: 2024,
    bidang: 'Sekretariat Dinas',
    fileName: 'Surat_Keputusan_Bupati_IKU_Transnaker_2024.pdf',
    fileType: 'pdf',
    fileSize: '1.4 MB',
    uploadedBy: 'Administrator SAKIP',
    uploadedAt: '2024-01-20 11:15',
    deskripsi: 'Surat Keputusan penetapan Indikator Kinerja Utama beserta manual indikator, formula perhitungan, dan target tahunan seluruh bidang.',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '188.45/42/BUP-LUTRA/2024',
  },
  {
    id: 'doc-pk',
    title: 'Perjanjian Kinerja (PK) Kepala Dinas Transnaker Tahun Anggaran 2024',
    kategori: 'PK',
    tahun: 2024,
    bidang: 'Sekretariat Dinas',
    fileName: 'Perjanjian_Kinerja_Kadis_Transnaker_2024.pdf',
    fileType: 'pdf',
    fileSize: '950 KB',
    uploadedBy: 'Administrator SAKIP',
    uploadedAt: '2024-01-10 14:00',
    deskripsi: 'Perjanjian Kinerja tahun berjalan antara Kepala Dinas Transmigrasi dan Tenaga Kerja dengan Bupati Luwu Utara.',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '560/PK-01/TRANSNAKER/2024',
  },
  {
    id: 'doc-renja',
    title: 'Rencana Kerja (RENJA) Tahunan dan RKT Dinas Transnaker 2024',
    kategori: 'RENJA',
    tahun: 2024,
    bidang: 'Sekretariat Dinas',
    fileName: 'Matriks_RENJA_RKT_Transnaker_2024.xlsx',
    fileType: 'xlsx',
    fileSize: '1.2 MB',
    uploadedBy: 'Operator Perencanaan & Keuangan',
    uploadedAt: '2024-02-18 10:20',
    deskripsi: 'Matriks Rencana Kerja Tahunan memuat alokasi program, kegiatan, subkegiatan, target indikator dan pagu anggaran DPA.',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '560/082/RENJA/2024',
    previewRows: [
      ['Kode Rekening', 'Program / Kegiatan / Sub Kegiatan', 'Indikator Kinerja', 'Target', 'Satuan', 'Pagu Anggaran (Rp)'],
      ['1.08.01', 'Program Penunjang Urusan Pemda (Sekretariat)', 'Persentase Layanan Perkantoran Optimal', '100', '%', '2.450.000.000'],
      ['1.08.02', 'Program Penempatan & Perluasan Kerja (Bidang Pemberdayaan)', 'Jumlah Tenaga Kerja Bersertifikat BNSP', '160', 'Orang', '620.000.000'],
      ['1.08.03', 'Program Fasilitasi Hubungan Industrial (Bidang Hubungan Industrial)', 'Pencegahan dan Penyelesaian Perselisihan HI', '100', '%', '310.000.000'],
      ['1.08.04', 'Program Penyiapan Kawasan Transmigrasi (Bidang Penyiapan & Pembangunan)', 'Infrastruktur UPT & Legalitas Lahan', '85', '%', '750.000.000'],
      ['1.08.05', 'Program Pengembangan Transmigrasi (Bidang Pengembangan Kawasan)', 'Peningkatan Kemandirian Kawasan Transmigrasi', '80', '%', '850.000.000'],
    ],
  },
  {
    id: 'doc-pelatihan',
    title: 'Laporan Pelaksanaan Pelatihan Vokasi & Penempatan Tenaga Kerja Luwu Utara 2024',
    kategori: 'LAINNYA',
    tahun: 2024,
    bidang: 'Bidang Pemberdayaan Tenaga Kerja',
    fileName: 'Laporan_Pelatihan_dan_Penempatan_Tenaga_Kerja_2024.pdf',
    fileType: 'pdf',
    fileSize: '2.4 MB',
    uploadedBy: 'Operator Bidang Pemberdayaan Tenaga Kerja',
    uploadedAt: '2024-05-12 14:15',
    deskripsi: 'Data rekapan peserta pelatihan berbasis kompetensi di BLK Luwu Utara dan penyaluran tenaga kerja ke sektor formal & UMKM.',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '560/118/PEMBERDAYAAN-TK/2024',
  },
  {
    id: 'doc-sop-hi',
    title: 'Standar Operasional Prosedur (SOP) Mediasi Perselisihan Hubungan Industrial & UMK',
    kategori: 'SOP',
    tahun: 2024,
    bidang: 'Bidang Hubungan Industrial',
    fileName: 'SOP_Penyelesaian_Perselisihan_Hubungan_Industrial_2024.pdf',
    fileType: 'pdf',
    fileSize: '1.8 MB',
    uploadedBy: 'Operator Bidang Hubungan Industrial',
    uploadedAt: '2024-03-01 11:00',
    deskripsi: 'Petunjuk teknis fasilitasi pembentukan LKS Bipartit, pengawasan norma kerja, dan mekanisme mediasi perselisihan ketenagakerjaan.',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '560/SOP-HI/TRANSNAKER/2024',
  },
  {
    id: 'doc-ded-trans',
    title: 'Dokumen Teknis Penyiapan Lahan & Pembangunan Sarana Prasarana UPT Transmigrasi',
    kategori: 'LAINNYA',
    tahun: 2024,
    bidang: 'Bidang Penyiapan dan Pembangunan Kawasan Transmigrasi',
    fileName: 'DED_Penyiapan_Lahan_dan_Jalan_Kawasan_Transmigrasi.pdf',
    fileType: 'pdf',
    fileSize: '4.6 MB',
    uploadedBy: 'Operator Bidang Penyiapan & Pembangunan Kawasan',
    uploadedAt: '2024-04-18 10:45',
    deskripsi: 'Detail Engineering Design (DED) penataan pemukiman transmigrasi, fasilitasi legalitas Hak Pengelolaan Lahan (HPL), dan infrastruktur air bersih.',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '560/DED-TRANS/PPKT/2024',
  },
  {
    id: 'doc-kemandirian-trans',
    title: 'Laporan Evaluasi Indeks Perkembangan Kawasan Transmigrasi (IPKT) Luwu Utara 2024',
    kategori: 'MONEV',
    tahun: 2024,
    bidang: 'Bidang Pengembangan Kawasan Transmigrasi',
    fileName: 'Evaluasi_Indeks_Perkembangan_Transmigrasi_Lutra_2024.xlsx',
    fileType: 'xlsx',
    fileSize: '980 KB',
    uploadedBy: 'Operator Bidang Pengembangan Kawasan',
    uploadedAt: '2024-06-25 15:30',
    deskripsi: 'Matriks pengukuran kemandirian ekonomi, sosial budaya, dan kelembagaan warga transmigrasi menuju Kawasan Transmigrasi Mandiri (KTM).',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '560/IPKT-BANGTRANS/2024',
    previewRows: [
      ['Kawasan / UPT', 'Jumlah KK', 'Status Kemandirian', 'Skor IPKT', 'Sektor Unggulan', 'Kebutuhan Intervensi'],
      ['UPT Lantang Tallang', '150', 'Transmigrasi Berkembang', '74.2', 'Kakao & Hortikultura', 'Penguatan Koperasi Unit Desa'],
      ['UPT Salulemo', '200', 'Transmigrasi Mandiri', '82.5', 'Kelapa Sawit & Padi Sawah', 'Peningkatan Akses Pasar Digital'],
      ['UPT Bone Subur', '125', 'Transmigrasi Pemula', '63.8', 'Jagung & Peternakan', 'Bantuan Bibit & Pupuk Bersubsidi'],
    ],
  },
  {
    id: 'doc-lkjip',
    title: 'Laporan Kinerja Instansi Pemerintah (LKjIP) Dinas Transnaker Tahun 2023',
    kategori: 'LKjIP',
    tahun: 2023,
    bidang: 'Sekretariat Dinas',
    fileName: 'LKjIP_Dinas_Transnaker_Luwu_Utara_2023_Final.pdf',
    fileType: 'pdf',
    fileSize: '5.2 MB',
    uploadedBy: 'Administrator SAKIP',
    uploadedAt: '2024-02-28 16:45',
    deskripsi: 'Laporan pertanggungjawaban akuntabilitas kinerja tahunan Dinas Transnaker memuat capaian sasaran strategis, kendala, dan rekomendasi.',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '560/LKJIP-2023/DIS-TRANSNAKER',
  },
  {
    id: 'doc-renaksi',
    title: 'Matriks Rencana Aksi (RENAKSI) Capaian Kinerja Triwulan III 2024',
    kategori: 'RENAKSI',
    tahun: 2024,
    bidang: 'Sekretariat Dinas',
    fileName: 'Matriks_Rencana_Aksi_TW3_Transnaker_2024.xlsx',
    fileType: 'xlsx',
    fileSize: '840 KB',
    uploadedBy: 'Operator Perencanaan & Keuangan',
    uploadedAt: '2024-07-08 13:10',
    deskripsi: 'Lembar kerja rencana aksi pentahapan target fisik dan keuangan serta penanggung jawab 5 bidang per triwulan.',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '560/RENAKSI-TW3/2024',
    previewRows: [
      ['Sasaran', 'Unit Kerja Penanggung Jawab', 'Target TW III', 'Realisasi TW III', 'Capaian (%)', 'Kendala Lapangan', 'Tindak Lanjut'],
      ['Kualitas Tenaga Kerja', 'Bidang Pemberdayaan Tenaga Kerja', '120', '128', '106.6%', 'Tingginya animo pendaftar kejuruan las', 'Penambahan kuota kelas kemitraan industri'],
      ['Hubungan Industrial Harmonis', 'Bidang Hubungan Industrial', '20', '21', '105.0%', 'Jarak jangkau ke perkebunan sawit terpencil', 'Fasilitasi mediasi keliling berbasis kecamatan'],
      ['Penyiapan Lahan UPT', 'Bidang Penyiapan dan Pembangunan Kawasan Transmigrasi', '50', '48', '96.0%', 'Proses pengukuran batas bersama BPN', 'Koordinasi intensif bersama Gugus Tugas Reforma Agraria'],
      ['Kemandirian Ekonomi UPT', 'Bidang Pengembangan Kawasan Transmigrasi', '80', '82', '102.5%', 'Akses permodalan kelompok tani', 'Fasilitasi kemitraan KUR Pertanian'],
    ],
  },
  {
    id: 'doc-monev',
    title: 'Laporan Monitoring dan Evaluasi (MONEV) Kinerja Triwulan II 2024',
    kategori: 'MONEV',
    tahun: 2024,
    bidang: 'Sekretariat Dinas',
    fileName: 'Laporan_Monev_Triwulan_II_2024_Transnaker.pdf',
    fileType: 'pdf',
    fileSize: '2.1 MB',
    uploadedBy: 'Operator Perencanaan & Keuangan',
    uploadedAt: '2024-07-15 08:40',
    deskripsi: 'Laporan berkala hasil monitoring capaian IKP, IKK, dan serapan anggaran periode April s.d Juni 2024 seluruh bidang dinas.',
    statusVerifikasi: 'Terverifikasi',
    nomorSurat: '560/MONEV-TW2/2024',
  },
];
